name: stack-core

networks:
  my-network-public:
    name: my-network-public
    external: false
  my-network-proxy:
    name: my-network-proxy
    external: false

services:
  port:
    image: portainer/portainer-ce:2.33.0-alpine
    restart: always
    networks:
      - my-network-public
      - my-network-proxy
    expose:
      - 9000
      - 9443
    ports:
      - 9000:9000
    volumes:
      - /var/mnt-links/docker/portainer/data:/data
      - /var/mnt-links/docker/dind-dev/var/run:/var/dind-dev-run/
      - /var/run/docker.sock:/var/run/docker.sock
