name: stack-core-docker

networks:
  my-network-public:
    name: my-network-public
    external: true

services:
  dind-dev:
    image: docker:28.3.0-dind
    restart: always
    privileged: true
    hostname: dind-dev
    networks:
      - my-network-public
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - /mnt-links/docker/dind-dev/certs:/certs
      - /mnt-links/docker/dind-dev/var/lib/docker:/var/lib/docker
      - /mnt-links/docker/dind-dev/var/run:/var/run
      - /mnt-links/docker-dev:/mnt-links/docker
      - /mnt-links/media-dev:/mnt-links/media
