name: stack-portainer

networks:
  my-netwotk-core:
    name: my-netwotk-core
    external: false
  my-network-public:
    name: my-network-public
    external: false

volumes:
  portainer-data:
    name: static-portainer-data
  dind-core-data:
    name: static-dind-core-data
  dind-core-run:
    name: static-dind-core-run

services:
  nginx-proxy:
    image: nginxproxy/nginx-proxy
    networks:
      - my-netwotk-core
      - my-network-public
    ports:
      - 80:80
      - 443:443
    environment:
      DEFAULT_HOST: localhost
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  port:
    image: portainer/portainer-ce:2.28.1-alpine
    restart: always
    networks:
      - my-network-public
    ports:
      - 9000:9000
    environment:
      - VIRTUAL_HOST=port.localhost
      - VIRTUAL_PORT=9000
      - VIRTUAL_PATH=/
      - VIRTUAL_DEST=/
    volumes:
      - portainer-data:/data
      - dind-core-run:/var/run-dind-core/

  dind-core:
    image: docker:28.0.2-dind
    restart: always
    privileged: true
    environment:
      - DOCKER_TLS_CERTDIR=/certs
    volumes:
      - dind-core-data:/var/lib/docker
      - dind-core-run:/var/run
