name: stack-appsmith

networks:
  my-network-public:
    name: my-network-public
    external: true

services:  
  appsmith:
    image: appsmith/appsmith-ee:v1.74
    restart: unless-stopped
    networks:
      - my-network-public
    expose:
      - 80
      - 443
    volumes:
      - /mnt-links/docker/appsmith/appsmith-stacks:/appsmith-stacks
    labels:
      virtual.title: appsmith
      virtual.url: http://appsmith.${USER_HOSTNAME:?error}
      virtual.host: appsmith.${USER_HOSTNAME:?error}
      virtual.upstream.port: 443
      virtual.upstream.protocol: http://
