name: stack-net-syncthing

networks:
  my-network-public:
    name: my-network-public
    external: true

services:
  syncthing:
    image: syncthing/syncthing:1.30.0
    restart: always
    networks:
      - my-network-public
    expose:
      - 8384 # Web UI
    ports:
      - 22000:22000/tcp # TCP file transfers
      - 22000:22000/udp # QUIC file transfers
      - 21027:21027/udp # Receive local discovery broadcasts
    environment:
      - STHOMEDIR=/var/syncthing/config
      - HOME=/var/syncthing/folders
    volumes:
      - /var/mnt-links/docker/syncthing/var/syncthing:/var/syncthing
    healthcheck:
      test: curl -fkLsS -m 2 127.0.0.1:8384/rest/noauth/health | grep -o --color=never OK || exit 1
      interval: 1m
      timeout: 10s
      retries: 3
    labels:
      virtual.caddyfile: |
        https://sync.${USER_HOSTNAME:?error} {
            redir http://sync.${USER_HOSTNAME:?error}
        }
        http://sync.${USER_HOSTNAME:?error} {
            reverse_proxy syncthing:8384 {
            }
        }
      virtual.homefile: |
        <div class="hire" style="margin: 5px;">
          <a class="shadow" href="http://sync.${USER_HOSTNAME:?error}">syncthing</a>
          <small>http://sync.${USER_HOSTNAME:?error}</small>
        </div>
