name: stack-cms-nocodb

networks:
  my-network-proxy:
    name: my-network-proxy
    external: true

services:  
  nocodb:
    image: nocodb/nocodb:0.264.6
    restart: unless-stopped
    networks:
      - my-network-proxy
    expose:
      - 8080
    volumes:
      - /var/mnt-links/docker/nocodb/usr/app/data:/usr/app/data
    labels:
      virtual.title: nocodb
      virtual.url: http://nocodb.cms.localhost
      virtual.caddyfile: |
        https://nocodb.cms.localhost {
            redir http://nocodb.cms.localhost
        }
        http://nocodb.cms.localhost {
            reverse_proxy nocodb:8080 {
            }
        }
      virtual.homefile: |
        <div>
          <a class="shadow" href="http://nocodb.cms.localhost">nocodb</a>
          <small>http://nocodb.cms.localhost</small>
        </div>
