name: stack-media-strapi

networks:
  my-network-public:
    name: my-network-public
    external: true

services:
  strapi:
    build:
      dockerfile_inline: |
        FROM node:22-alpine as build
        ENV NODE_ENV=production
        RUN apk add git curl
        WORKDIR /srv/app
        RUN curl -L https://github.com/strapi/strapi/archive/refs/tags/v5.18.1.zip >v5.18.1.zip && unzip v5.18.1.zip && cd ./strapi-5.18.1
        RUN npm install --only=production
        RUN npm run build

        FROM node:22-alpine
        ENV NODE_ENV=production
        WORKDIR /srv/app
        COPY --from=build /svr/strapi-5.18.1/ /srv/app
        
        EXPOSE 1337
        CMD ["npm", "run", "start"]
    restart: always
    # command: ["sleep", "99999999"]
    hostname: strapi.media.${USER_HOSTNAME:?error}
    networks:
      - my-network-public
    volumes:
      - /var/mnt-links/docker/strapi/srv/app:/srv/app
    expose:
      - 1337
    labels:
      virtual.caddyfile: |
        https://strapi.media.${USER_HOSTNAME:?error} {
            redir http://strapi.media.${USER_HOSTNAME:?error}
        }
        http://strapi.media.${USER_HOSTNAME:?error} {
            reverse_proxy strapi:1337 {
            }
        }
      virtual.homefile: |
        <div class="hire" style="margin: 5px;">
          <a class="shadow" href="http://strapi.media.${USER_HOSTNAME:?error}">strapi</a>
          <small>http://strapi.media.${USER_HOSTNAME:?error}</small>
        </div>
