name: stack-llm-openwebui

networks:
  my-network-proxy:
    name: my-network-proxy
    external: true

services:
  openwebui:
    image: ghcr.io/open-webui/open-webui:0.6.25
    restart: always    
    networks:
      - my-network-proxy
    expose:
      - 8080
    volumes:
      - /var/mnt-links/docker/open-webui/app/backend/data:/app/backend/data
    labels:
      virtual.caddyfile: |
        https://openwebui.llm.${USER_HOSTNAME:?error} {
            redir http://openwebui.${USER_HOSTNAME:?error}
        }
        http://openwebui.llm.${USER_HOSTNAME:?error} {
            reverse_proxy openwebui:8080 {
            }
        }
      virtual.homefile: |
        <div>
          <a class="shadow" href="http://openwebui.llm.${USER_HOSTNAME:?error}">Open Web UI</a>
          <small>http://openwebui.llm.${USER_HOSTNAME:?error}</small>
        </div>
