name: stack-media-nextcloud

networks:
  my-network-public:
    name: my-network-public
    external: true

services:
  nextcloud:
    image: nextcloud:31.0.6
    restart: no
    hostname: nextcloud.media.${USER_HOSTNAME:?error}
    networks:
      - my-network-public
    volumes:
      - /mnt-links/docker/nextcloud/var/www/html:/var/www/html
    expose:
      - 80
    labels:
      virtual.caddyfile: |
        https://nextcloud.media.${USER_HOSTNAME:?error} {
            redir http://nextcloud.media.${USER_HOSTNAME:?error}
        }
        http://nextcloud.media.${USER_HOSTNAME:?error} {
            reverse_proxy nextcloud:80 {
            }
        }
      virtual.homefile: |
        <div class="hire" style="margin: 5px;">
          <a class="shadow" href="http://nextcloud.media.${USER_HOSTNAME:?error}">nextcloud</a>
          <small>http://nextcloud.media.${USER_HOSTNAME:?error}</small>
        </div>

  collaboracode:
    image: collabora/code:25.04.3.2.1
    restart: no
    hostname: collaboracode.media.${USER_HOSTNAME:?error}
    networks:
      - my-network-public
    expose:
      - 9980
    environment:
      - server_name=collaboracode.media.${USER_HOSTNAME:?error}
      - aliasgroup1=http://nextcloud.media.${USER_HOSTNAME:?error}
      - domain=collaboracode.media.${USER_HOSTNAME:?error}
      - username=admin
      - password=admin
      - extra_params=--o:ssl.enable=false --o:ssl.termination=false --o:logging.level=warning
    labels:
      virtual.caddyfile: |
        https://collaboracode.media.${USER_HOSTNAME:?error} {
            redir http://collaboracode.media.${USER_HOSTNAME:?error}
        }
        http://nextcloud.media.${USER_HOSTNAME:?error} {
            reverse_proxy collaboracode:9980 {
            }
        }
      virtual.homefile: |
        <div class="hire" style="margin: 5px;">
          <a class="shadow" href="http://collaboracode.media.${USER_HOSTNAME:?error}">collaboracode</a>
          <small>http://collaboracode.media.${USER_HOSTNAME:?error}</small>
        </div>
