name: stack-cms-n8n

networks:
  my-network-public:
    name: my-network-public
    external: true

services:
  n8n:
    image: docker.n8n.io/n8nio/n8n:1.107.2
    restart: no
    networks:
      - my-network-public
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=
      - N8N_SECURE_COOKIE=false
    volumes:
      - /var/mnt-links/docker/n8n/home/node/.n8n:/home/node/.n8n
    expose:
      - 5678
    labels:
      virtual.caddyfile: |
        https://n8n.cms.${USER_HOSTNAME:?error} {
            redir http://n8n.cms.${USER_HOSTNAME:?error}
        }
        http://n8n.cms.${USER_HOSTNAME:?error} {
            reverse_proxy n8n:5678 {
            }
        }
      virtual.homefile: |
        <div class="hire" style="margin: 5px;">
          <a class="shadow" href="http://n8n.cms.${USER_HOSTNAME:?error}">N8n</a>
          <small>http://n8n.cms.${USER_HOSTNAME:?error}</small>
        </div>
